/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3390

export {}

declare module '*.vue' {
  const component: Vue.ComponentOptions<Vue.Component>
  export default component
}